# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAssignment2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_assignment2(self):
    # Test name: Assignment2
    # Step # | name | target | value
    # 1 | open | https://the-internet.herokuapp.com/login | 
    self.driver.get("https://the-internet.herokuapp.com/login")
    # 2 | type | id=username | tomsmith
    self.driver.find_element(By.ID, "username").send_keys("tomsmith")
    # 3 | type | id=password | SuperSecretPassword!
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    # 4 | click | css=.fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 5 | verifyElementPresent | linkText=Logout | 
    elements = self.driver.find_elements(By.LINK_TEXT, "Logout")
    assert len(elements) > 0
    # 6 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
