# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAssignment1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_assignment1(self):
    # Test name: Assignment1
    # Step # | name | target | value
    # 1 | open | https://www.amazon.in | 
    self.driver.get("https://www.amazon.in")
    # 2 | waitForElementVisible | id=nav-logo-sprites | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "nav-logo-sprites")))
    # 3 | executeScript | return document.title | pageTitle
    self.vars["pageTitle"] = self.driver.execute_script("return document.title")
    # 4 | echo | ${pageTitle}  | 
    print("\n")
    print("{} ".format(self.vars["pageTitle"]))
    assert self.vars['pageTitle'] == "Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in"
  
