# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3(self):
    # Test name: lab_3
    # Step # | name | target | value
    # 1 | open | http://demo.opencart.com/ | 
    self.driver.get("http://demo.opencart.com/")
    # 2 | click | css=.navbar-toggler | 
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    # 3 | click | linkText=Desktops | 
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    # 4 | click | linkText=Mac (1) | 
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    # 5 | click | id=input-sort | 
    self.driver.find_element(By.ID, "input-sort").click()
    # 6 | select | id=input-sort | label=Name (A - Z)
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    # 7 | click | css=#input-sort > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#input-sort > option:nth-child(2)").click()
    # 8 | click | linkText=iMac | 
    self.driver.find_element(By.LINK_TEXT, "iMac").click()
    # 9 | click | id=button-cart | 
    self.driver.find_element(By.ID, "button-cart").click()
    # 10 | close |  | 
    self.driver.close()
  
