# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab4():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab4(self):
    # Test name: lab_4
    # Step # | name | target | value
    # 1 | open | https://tutorialsninja.com/demo | 
    self.driver.get("https://tutorialsninja.com/demo")
    # 2 | verifyTitle | Your Store | 
    assert self.driver.title == "Your Store"
    # 3 | click | linkText=Desktops | 
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    # 4 | click | linkText=Mac (1) | 
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    # 5 | verifyTitle | Mac | 
    assert self.driver.title == "Mac"
    # 6 | click | id=input-sort | 
    self.driver.find_element(By.ID, "input-sort").click()
    # 7 | select | id=input-sort | label=Name (A - Z)
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    # 8 | click | css=#input-sort > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#input-sort > option:nth-child(2)").click()
    # 9 | click | css=.button-group .fa-shopping-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-group .fa-shopping-cart").click()
    # 10 | click | name=search | 
    self.driver.find_element(By.NAME, "search").click()
    # 12 | click | css=.input-group-btn > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".input-group-btn > .btn").click()
    # 14 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 15 | click | id=button-search | 
    self.driver.find_element(By.ID, "button-search").click()
  
