# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab1(self):
    # Test name: lab_1
    # Step # | name | target | value
    # 1 | open | https://www.google.com | 
    self.driver.get("https://www.google.com")
    # 4 | verifyElementPresent | css=.HTOhZ | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".HTOhZ")
    assert len(elements) > 0
  
